### PR TITLE
Set response CORS headers if not already present

### PR DESCRIPTION
**Pull request by mderriey**
When a valid token is found in the request but the scope requirement isn't met,
CORS headers are set on the response from the values of several request headers.
This potentially conflicts if CORS headers were already set on the response,
for example by the CORS middleware.

### CODE REVIEW

**Comment by leastprivilege** [comment]
https://ci.appveyor.com/project/leastprivilege/thinktecture-identityserver-v3-accesstokenvalidati/build/2.0.80

**Comment by mderriey** [comment]
sorry about that

**Comment by leastprivilege** [comment]
for the 3-series we decided to stay on C# 5. (for now)

**Comment by leastprivilege** [comment]
thanks!

**Comment by mderriey** [comment]
Have you tried playing with the `$psake.build_success` variable in `build.ps1` to fail the build when there's an error in the process?
I can see you [asked about it already](http://help.appveyor.com/discussions/questions/828-psake-failed-builds-are-marked-as-success).

Happy to try fixing this even though we'll have to trial and error as `$LASTEXITCODE` is `1` when the build fails on my local machine.

**Comment by leastprivilege** [comment]
Give it a go. I am mostly interested in this for the main identityserver repo (as a start at least)

**Pull request merged**
